project_name: dojimamint

env:
  # Require use of Go modules.
  - GO111MODULE=on

builds:
  - id: "Tendermint"
    main: ./cmd/dojimamint/main.go
    ldflags:
      - -s -w -X github.com/dojimamint/dojimamint/version.TMCoreSemVer={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

release:
  name_template: "{{.Version}} (WARNING: BETA SOFTWARE)"
